### ISSUE TITLE
Impossible to use Theia backend with external server

### ISSUE THREAD

**Issue by xbit18** [eclipse-glsp/glsp#1110] opened 2023-09-04 18:24 UTC
I've tried many times to start the tasklist example and also the workflow example, having the Theia backend separate from the glsp server. 
I've used every combination possible of ports and websocket, every launch configuration inside VSCode, but nothing seems to work. 

The server starts fine, it listens on port 5007. 
When I start the Theia backend (with external glsp server) from the launch configuration in VSCode (or in other ways) it seems to start fine, but when I load the page at localhost:3000, the example doesn't load and I get this error
![image](https://github.com/eclipse-glsp/glsp/assets/38242794/445c08f3-26b0-4762-a0a6-1a4c50f0950e)
I've tried using different browsers but it makes no difference.

This is the stack trace inside the output tab in VSCode:
C:\Program Files\nodejs\node.exe .\tasklist-browser-app\src-gen\backend\main.js --port=3000 --no-cluster --TASKLIST_GLSP=5007 --debug --app-project-path=E:\ProvaGLSP\glsp-examples\project-templates\java-emf-theia\glsp-client/tasklist-browser-app --root-dir=E:\ProvaGLSP\glsp-examples\project-templates\java-emf-theia\glsp-client/workspace
Debugger attached.
Configuration directory URI: 'file:///c%3A/Users/xbit1/.theia'
2023-09-04T18:21:01.905Z root INFO Backend Object.initialize: 12.9 ms [Finished 2.839 s after backend start]
2023-09-04T18:21:01.905Z root INFO Backend Object.configure: 11.3 ms [Finished 2.839 s after backend start]
2023-09-04T18:21:01.905Z root INFO Backend MessagingContribution.onStart: 2.8 ms [Finished 2.839 s after backend start]
2023-09-04T18:21:01.905Z root INFO Backend OSBackendApplicationContribution.configure: 0.6 ms [Finished 2.863 s after backend start]
2023-09-04T18:21:01.907Z root INFO Backend LocalizationBackendContribution.initialize: 25.2 ms [Finished 2.865 s after backend start]
2023-09-04T18:21:01.907Z root INFO Backend LocalizationBackendContribution.configure: 0.5 ms [Finished 2.865 s after backend start]
2023-09-04T18:21:01.909Z root INFO Backend NodeFileUploadService.configure: 2.4 ms [Finished 2.868 s after backend start]
2023-09-04T18:21:01.909Z root INFO Backend FileDownloadEndpoint.configure: 0.9 ms [Finished 2.869 s after backend start]
2023-09-04T18:21:01.914Z root INFO Theia app listening on http://localhost:3000.
2023-09-04T18:21:01.919Z root INFO Backend DefaultWorkspaceServer.onStart: 16.7 ms [Finished 2.879 s after backend start]
2023-09-04T18:21:01.920Z root INFO Finished starting backend application: 0.1 ms [Finished 2.880 s after backend start]
2023-09-04T18:21:41.244Z root WARN Frontend CommonFrontendContribution.configure took longer than the expected maximum 100 milliseconds: 148.0 ms [Finished 1.395 s after frontend start]
2023-09-04T18:21:41.245Z root WARN A command editor.action.toggleStickyScroll is already registered.
2023-09-04T18:21:41.517Z root WARN Failed to resolve module: @theia/electron
2023-09-04T18:21:41.526Z root INFO Detected keyboard layout from browser API: US (PC)
2023-09-04T18:21:41.634Z root WARN Linked preference "workbench.colorCustomizations" not found. Source: "editor.bracketPairColorization.enabled"
2023-09-04T18:21:41.634Z root WARN Linked preference "window.titleBarStyle" not found. Source: "window.menuBarVisibility"
2023-09-04T18:21:41.687Z root WARN Frontend EditorNavigationContribution.onStart took longer than the expected maximum 100 milliseconds: 350.5 ms [Finished 1.850 s after frontend start]
2023-09-04T18:21:41.745Z root INFO Start frontend contributions: 686.2 ms [Finished 1.902 s after frontend start]
2023-09-04T18:21:41.745Z root INFO Changed application state from 'init' to 'started_contributions'.
2023-09-04T18:21:41.764Z root INFO Changed application state from 'started_contributions' to 'attached_shell'.
2023-09-04T18:21:41.766Z root INFO >>> Restoring the layout state...
2023-09-04T18:21:41.800Z root INFO <<< The layout has been successfully restored.
2023-09-04T18:21:41.803Z root INFO Initialize the workbench layout: 47.5 ms [Finished 1.965 s after frontend start]
2023-09-04T18:21:41.803Z root INFO Changed application state from 'attached_shell' to 'initialized_layout'.
2023-09-04T18:21:41.823Z root ERROR [JsonrpcGLSPClient] Connection to server got closed. Server will not be restarted. []
2023-09-04T18:21:42.626Z root INFO Frontend application start: 1400.9 ms [Finished 43.586 s after backend start]
2023-09-04T18:21:42.627Z root INFO Replace loading indicator with ready workbench UI (animation): 824.2 ms [Finished 2.790 s after frontend start]
2023-09-04T18:21:42.627Z root INFO Changed application state from 'initialized_layout' to 'ready'.

**Comment by tortmayr** [comment] 2023-09-04 21:32
Potential duplicate of https://github.com/eclipse-glsp/glsp/issues/1100

**Closed** 2024-03-26 22:10 UTC
Labels: bug
