### ISSUE TITLE
glsp-eclipse-integration server subproject does not compile

### ISSUE THREAD

**Issue by JuergenMutschall** [eclipse-glsp/glsp#236] opened 2021-05-14 17:06 UTC
Hello,

I tried to follow the Readme.md:

git clone https://github.com/eclipse-glsp/glsp-eclipse-integration.git
cd glsp-eclipse-integration
cd server
mvn clean install

error:

--- tycho-compiler-plugin:2.1.0:compile (default-compile) @ org.eclipse.glsp.ide.editor ---
[INFO] Compiling 53 source files to /home/juergen/glsp-eclipse-integration/server/plugins/org.eclipse.glsp.ide.editor/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for GLSP Eclipse IDE Integration Parent 0.9.0-SNAPSHOT:
[INFO]
[INFO] GLSP Eclipse IDE Integration Parent ................ SUCCESS [  0.084 s]
[INFO] org.eclipse.glsp.ide.editor ........................ FAILURE [  1.366 s]
[INFO] org.eclipse.glsp.ide.workflow.editor ............... SKIPPED
[INFO] GLSP Eclipse IDE Integration Releng ................ SKIPPED
[INFO] org.eclipse.glsp.codestyle ......................... SKIPPED
[INFO] org.eclipse.glsp.ide.feature ....................... SKIPPED
[INFO] org.eclipse.glsp.ide.repository .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.269 s
[INFO] Finished at: 2021-05-14T19:01:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.1.0:compile (default-compile) on project org.eclipse.glsp.ide.editor: Compilation failure: Compilation failure:
[ERROR] /home/juergen/glsp-eclipse-integration/server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/actions/handlers/IdeSaveModelActionHandler.java:[27]
[ERROR]         protected Optional<File> convertToFile(final GModelState modelState) {
[ERROR]                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method convertToFile(GModelState) of type IdeSaveModelActionHandler must override or implement a supertype method
[ERROR] 1 problem (1 error)

Best Regards

Jürgen

**Comment by planger** [comment] 2021-05-20 09:02
Thanks for the report!

I just tried building the current master and couldn't reproduce the build error. Also after clearing my local .m2 cache it worked.
From the error it looks like that the resolved target is not up to date. Maybe there is some old cache in your system?
Also you could try something like `mvn clean install -U` or `mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false`
If nothing helps, you can try clearing your .m2/repository folder as well.

Please let us know if the problem persists!

**Comment by planger** [comment] 2021-06-11 08:38
As we can't reproduce this error and didn't get feedback, we'll close this issue for now. Please feel free to re-open it if you have further input. Thanks!

**Closed by planger** 2021-06-11 08:38 UTC
Labels: eclipse
