### ISSUE TITLE
GLSP Example Server should be started by Backend

### ISSUE THREAD

**Issue by eneufeld** [eclipse-glsp/glsp#78] opened 2020-06-04 12:24 UTC
The GLSP Example Server should be started by the backend.
By starting the server in the backend we can change the server to shutdown when the connection is closed instead of allowing many subsequent connections.
Furthermore we don't need to cleanup the server as the processed will be stopped.

**Comment by tortmayr** [comment] 2020-07-01 10:49
Potential duplicate of #35

**Comment by tortmayr** [comment] 2020-08-15 16:57
Closing this. Duplicate of #35

**Closed by tortmayr** 2020-08-15 16:57 UTC
