### ISSUE TITLE
Make it easier to overwrite `GLSPDiagramWidget`

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#1064] opened 2023-07-19 19:35 UTC
See also https://github.com/eclipse-glsp/glsp/discussions/1060
It takes quite a lot of code to overwrite `GLSPDiagramWidget`, which is a quite common customization.
It would be rather easy to turn this into an injectable factory.

**Comment by tortmayr** [comment] 2023-07-19 19:44
I'm on it. Will be handled as part of https://github.com/eclipse-glsp/glsp/issues/587.
PR will be opened soonish so the change should be contained in the 2.0 Release.
This change switches to an injectable factory for the diagram widget and in addition introduces `DiagramInitializers` (WIP name) which  are services that are executed directly after the diagram container has been constructed and can be used to dispatch additional initial actions.
So in the future it is not even necessary to customize the diagram widget anymore.

**Comment by tortmayr** [comment] 2023-07-19 19:44
Closing this as duplicate of https://github.com/eclipse-glsp/glsp/issues/587

**Closed** 2023-09-04 22:16 UTC
Labels: enhancement
