### ISSUE TITLE
Routing Point can not be moved

### ISSUE THREAD

**Issue by rsoika** [eclipse-glsp/glsp#657] opened 2022-05-22 08:21 UTC
I observer some kind of Bug regarding the Routing points in an Edge. I am not sure if this is related to Sprotty, if so, I will move this issue. Also maybe the bug is already known and I am using only an old glsp client version - 0.10.0-next.385713d.170 ?

**Problem description:**

If you place an edge between to nodes in line and than select the edge, you will see 3 routing points. 
- the start point
- the end point
- and a virtual routing point in the middle.

You can't move the virtual routing point in the middle. And in deed the edge did not have any routing point. The collection is empty  in such a situation.

If you than move one element the routing changes and now you can see 5 Routing Points

- the start point
- the end point
- one real existing Routing Point which is relevant for the model
- and two virtual routing points in the middle of each section

From now on everything works like expected. You can move all 3 routing points and the ChangeRoutingPointsOperation event is send correctly providing 1(!) new routing Point.

If you move the element now back in line and move the routing points so that you have again a direct connection the problem occurs again - now the edge has again no more routing point (which is correct) but you can not grap the virtual routing point with the mouse.

![Peek 2022-05-22 10-07](https://user-images.githubusercontent.com/1339124/169685372-5937c341-40c7-4567-b3f7-96b0b34d48f2.gif)

**Comment by tortmayr** [comment] 2022-05-23 14:31
Thanks for reporting this. It looks to me like this is a bug in GLSP when using `manhattan` routing. Everything works as expected for `polyline` routing but with `manhattan` I can reproduce the issue:
![Peek 2022-05-23 16-28](https://user-images.githubusercontent.com/2311075/169842560-5b73bda4-8237-4b1a-a6f8-9e3de128991f.gif)

**Comment by martin-fleck-at** [comment] 2022-09-09 09:57
Turns out this is actually a bug in Sprotty itself. I opened a bug there: https://github.com/eclipse/sprotty/issues/310

**Comment by martin-fleck-at** [comment] 2022-12-06 16:03
@rsoika I close this issue as the original problem is solved if that is fine with you. If we need a better user experience, please feel free to open another issue.

**Closed by martin-fleck-at** 2022-12-06 16:03 UTC
Labels: bug
