### ISSUE TITLE
[Eclipse] Focus issue when opening two editor side-by-side 

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#162] opened 2020-12-10 10:31 UTC
When opening 2 Editors side by side, then selecting a node from the inactive editor, the editor doesn't grab focus; so all key-bindings are still delegated to the other editor.

When selecting the editor directly (by clicking its tab), it becomes active, and then selecting elements in the other editor switches the focus as expected (Which means bindings work as expected, too).

So the issue only seems to happen immediately after opening the editors, and remains until we specifically click on the Editor Tab (To force-focus it). After that, focus moves from one editor to the other as expected.

Long gif, showing the problem, and how to work around it by selecting the editor-tab:

![101759790-55b2e100-3ada-11eb-9061-f4b69c8f57b0](https://user-images.githubusercontent.com/19170971/101760433-2355b380-3adb-11eb-98d8-a26517bd9fff.gif)

**Comment by jfaltermeier** [comment] 2021-01-07 10:33
Root cause is probably this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567629
As it requires both changes to the SWT code and a chromium version update we can only work around this issue for now and have to clean up the workaround once a fix is released.

**Comment by tortmayr** [comment] 2023-01-20 12:23
Fixed with  https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/18

**Closed by tortmayr** 2023-01-20 12:23 UTC
Labels: eclipse
